feature/WAL-642
Sphereon-Opensource/did-siop-auth-web-demo pull request #21
Opened 2023-10-03 10:16 UTC by BtencateSphereon

some commits ended up in WAL-641 which this branch is based off. asked sadjad to revert that so we get decent PR's and reviews

2023-10-03 17:04 UTC, nklomp commented
Please merge in develop and adjust your VCI metadata if the merge doesn't already take care of it

2023-10-03 17:05 UTC, nklomp requested changes
Please merge in develop and adjust your VCI metadata if the merge doesn't already take care of it

2023-10-03 17:05 UTC, nklomp commented on packages/oid4vci-demo-frontend/src/configs/coc.json
> +    "credentialName": "Sphereon Guest",
Please merge and look at develop for proper values in this section

2023-10-04 08:30 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/configs/coc.json
> +    "credentialName": "Sphereon Guest",
metadata has been changed to:

"general": {
    "credentialName": "CoC credential",
    "issueCredentialType": "KvkInschrijving",
    "baseUrl": "https://kvk.demo.sphereon.com/agent",
    "verifierUrl": "https://sphereon.com",
    "verifierUrlCaption": "CoC credential",
    "downloadUrl": "https://kvk.demo.sphereon.com/agent/#/download"
  },

2023-10-04 08:31 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/configs/coc.json
> +    "credentialName": "Sphereon Guest",
not sure about the verifierUrl

2023-10-04 08:34 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/configs/coc.json
> +    "credentialName": "Sphereon Guest",
updateed verifierUrl to https://kvk.demo.sphereon.com/verifier

2023-10-04 11:05 UTC, nklomp commented on packages/oid4vci-demo-frontend/src/configs/coc.json
> +    "credentialName": "Sphereon Guest",
Please change CoC credential for both to KvK Inschrijving. Domain values should all be in Dutch

2023-10-04 11:39 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/configs/coc.json
> +    "credentialName": "Sphereon Guest",
updated

2023-10-04 11:41 UTC, nklomp approved these changes

2023-10-04 11:41 UTC, nklomp commented
PR approved

2023-10-04 11:41 UTC, merged