Feature/vdx 261 switch env
Sphereon-Opensource/did-siop-auth-web-demo pull request #45
Opened 2023-10-13 14:24 UTC by sanderPostma

DRAFT FOR SELF-REVIEW

2023-10-16 13:32 UTC, BtencateSphereon requested changes
mostly beauty remarks and a question why we need a process package. i think i need to see a functional demo to fully finish my review

2023-10-16 13:32 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/package.json
> +    "process": "^0.11.10",
why do we need this? we were already using process without this package

2023-10-16 13:32 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/components/SSICardView/index.tsx
> +import React, {useState} from 'react'
unused import

2023-10-16 13:32 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/components/SSIPrimaryButton/index.tsx
> +import React, {useState} from 'react'
useState is unused

2023-10-16 13:32 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/ecosystem/ecosystem.ts
> +    getEcosystemRoutes,
unused import

2023-10-16 13:32 UTC, BtencateSphereon commented on packages/oid4vci-demo-frontend/src/pages/SSICredentialIssueRequestPage/index.tsx
> +    const buttonConfig = ecosystem.getComponentConfig<SSISecondaryButtonConfig>('SSISecondaryButton')
unused

2023-10-16 18:42 UTC, sanderPostma commented on packages/oid4vci-demo-frontend/src/pages/SSICredentialIssueRequestPage/index.tsx
> +    const buttonConfig = ecosystem.getComponentConfig<SSISecondaryButtonConfig>('SSISecondaryButton')
That one was there already. fixed in next commit

2023-10-16 18:43 UTC, sanderPostma commented on packages/oid4vci-demo-frontend/src/components/SSICardView/index.tsx
> +import React, {useState} from 'react'
Ran import optimization on components

2023-10-16 18:43 UTC, sanderPostma commented on packages/oid4vci-demo-frontend/src/components/SSIPrimaryButton/index.tsx
> +import React, {useState} from 'react'
Ran import optimization

2023-10-16 18:43 UTC, sanderPostma commented on packages/oid4vci-demo-frontend/src/ecosystem/ecosystem.ts
> +    getEcosystemRoutes,
Ran import optimization

2023-10-17 07:28 UTC, BtencateSphereon approved these changes
LGTM

2023-10-17 07:29 UTC, merged